export const ROAD = [
  {
    id: 0,
    road: 'S1',
    district: 'Tân Phú',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường này có nhiều xe máy, xe ô tô',
    image: '/assets/images/covers/cover_1.jpg',
    postedAt: '2021-10-10',
    position: [{ lat: 10.79, lng: 106.67 }],
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    id: 1,
    road: 'Nguyễn Văn Linh',
    district: '7',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường này rộng và thông thoáng, có nhiều cao ốc',
    image: '/assets/images/covers/cover_2.jpg',
    postedAt: '2022-01-01',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    id: 2,
    road: 'Phạm Văn Đồng',
    district: 'Cầu Giấy',
    city: 'Hà Nội',
    description: 'Đoạn đường này gần các trường đại học, có nhiều quán ăn',
    image: '/assets/images/covers/cover_3.jpg',
    postedAt: '2022-02-14',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    road: 'Tô Ký',
    district: '12',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường thường xảy ra tai nạn',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    postedAt: '2023-04-13T13:12:23.413Z',
    image: '/assets/images/covers/cover_24.jpg',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    road: 'Võ Văn Kiệt',
    district: ' Bình Tân',
    city: 'Hồ Chí Minh',
    description: ' Có tình hình giao thông phức tạp và tỷ lệ tai nạn giao thông xảy ra cao',
    solution: 'Đồng loạt ra quân thực hiện các giải pháp nhằm kéo giảm tai nạn giao thông.',
    accident1: '3',
    accident2: '0',
    accident3: '2',
    accident4: '0',
    length: '21000',
    width: '60',
    type: 'Đường bộ',
    material: 'Nhựa đường',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '80km/h',
    condition: 'Không',
    feature: 'Tuyến đường trọng yếu',
    postedAt: '2023-04-13T17:35:06.111Z',
    image: '/assets/images/covers/cover_2.jpg',
  },

  {
    id: 6,
    road: 'Đại lộ Thăng Long',
    district: 'Cầu Giấy',
    city: 'Hà Nội',
    description:
      'Đại lộ Thăng Long là một tuyến đường chính của Hà Nội, nối liền từ ngoại thành Hà Nội vào trung tâm thành phố.',
    image: '/assets/images/covers/cover_6.jpg',
    postedAt: '2022-03-20',
    solution: 'Thường xuyên kiểm tra và bảo dưỡng đường bộ, tuyến đường để đảm bảo an toàn giao thông.',
    length: '30km',
    width: '6-12 làn đường',
    type: 'Đường cao tốc',
    material: 'Bê tông nhựa',
    start: '21.051165, 105.771274',
    end: '21.116925, 105.781581',
    speed: '80km/h',
    condition: 'Không',
    feature: 'Nối liền ngoại thành Hà Nội vào trung tâm thành phố',
    accident1: 1,
    accident2: 2,
    accident3: 3,
    accident4: 2,
  },
  {
    id: 7,
    road: 'Đại lộ Võ Văn Kiệt',
    district: 'Bình Tân',
    city: 'Hồ Chí Minh',
    description: 'Đại lộ Võ Văn Kiệt nối liền Quận 1 và Bình Tân, là tuyến đường chính của TP. Hồ Chí Minh.',
    image: '/assets/images/covers/cover_7.jpg',
    postedAt: '2022-04-05',
    solution:
      'Cải thiện cơ sở hạ tầng đường bộ, tăng cường giám sát và kiểm soát tốc độ xe cộ để giảm nguy cơ tai nạn giao thông.',
    length: '14km',
    width: '4-6 làn đường',
    type: 'Đường cao tốc',
    material: 'Bê tông nhựa',
    start: '10.7312, 106.6892',
    end: '10.7926, 106.7011',
    speed: '80km/h',
    condition: 'Không',
    feature: 'Là tuyến đường chính của TP. Hồ Chí Minh',
    accident1: 2,
    accident2: 3,
    accident3: 4,
    accident4: 5,
  },

  {
    id: 8,
    road: 'Cầu Thanh Trì',
    district: 'Hoàng Mai',
    city: 'Hà Nội',
    description:
      'Cầu Thanh Trì là cây cầu bắc qua sông Hồng nối liền quận Hoàng Mai và Gia Lâm. Cầu có vị trí quan trọng trong việc kết nối các tuyến đường phía Nam của Hà Nội với các khu vực phía Bắc.',
    image: '/assets/images/covers/cover_8.jpg',
    postedAt: '2022-06-18',
    solution:
      'Nâng cấp cầu để tăng khả năng chịu tải, sửa chữa đường bộ, tăng cường kiểm soát tốc độ xe cộ và hạn chế các phương tiện vận tải quá tải trọng.',
    length: '2.8km',
    width: '6 làn đường',
    type: 'Cầu bắc qua sông',
    material: 'Bê tông cốt thép',
    start: '20.9749, 105.8683',
    end: '21.0043, 105.8887',
    speed: '60km/h',
    condition: 'Trong tình trạng tốt',
    feature:
      'Là cầu bắc qua sông Hồng có vai trò quan trọng trong việc kết nối các tuyến đường phía Nam của Hà Nội với các khu vực phía Bắc.',
    accident1: 1,
    accident2: 2,
    accident3: 0,
    accident4: 1,
  },
];
localStorage.setItem('road', JSON.stringify(ROAD));
