export const ROAD_DATA_INIT = [
  {
    id: 0,
    road: 'S1',
    district: 'Tân Phú',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường này có nhiều xe máy, xe ô tô',
    image: '/assets/images/covers/cover_1.jpg',
    postedAt: '2021-10-10',
    position: { lat: 10.8115698, lng: 106.6194961 },
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    id: 1,
    road: 'Nguyễn Văn Linh',
    district: '7',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường này rộng và thông thoáng, có nhiều cao ốc',
    image: '/assets/images/covers/cover_2.jpg',
    postedAt: '2022-01-01',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    position: { lat: 10.7350983, lng: 106.7210797 },
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    id: 2,
    road: 'Phạm Văn Đồng',
    district: 'Cầu Giấy',
    city: 'Hà Nội',
    description: 'Đoạn đường này gần các trường đại học, có nhiều quán ăn',
    image: '/assets/images/covers/cover_3.jpg',
    postedAt: '2022-02-14',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    position: { lat: 21.0466919, lng: 105.7814725 },

    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    road: 'Tô Ký',
    district: '12',
    position: { lat: 10.8608163, lng: 106.6177427 },

    city: 'Hồ Chí Minh',
    description: 'Đoạn đường thường xảy ra tai nạn',
    solution: 'Giảm tốc độ khi đi qua đoạn đường này',
    length: '5000m',
    width: '5m',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '50km/h',
    condition: 'Không',
    feature: 'Nhiều học sinh vào giờ cao điểm',
    postedAt: '2023-04-13T13:12:23.413Z',
    image: '/assets/images/covers/cover_24.jpg',
    accident1: 2,
    accident2: 4,
    accident3: 5,
    accident4: 4,
  },
  {
    road: 'Võ Văn Kiệt',
    district: ' Bình Tân',
    city: 'Hồ Chí Minh',
    description: ' Có tình hình giao thông phức tạp và tỷ lệ tai nạn giao thông xảy ra cao',
    solution: 'Đồng loạt ra quân thực hiện các giải pháp nhằm kéo giảm tai nạn giao thông.',
    accident1: '3',
    accident2: '0',
    position: { lat: 10.723416, lng: 106.6135035 },

    accident3: '2',
    accident4: '0',
    length: '21000',
    width: '60',
    type: 'Đường bộ',
    material: 'Nhựa đường',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '80km/h',
    condition: 'Không',
    feature: 'Tuyến đường trọng yếu',
    postedAt: '2023-04-13T17:35:06.111Z',
    image: '/assets/images/covers/cover_2.jpg',
  },
  {
    id: 6,
    road: 'Đại lộ Thăng Long',
    district: 'Cầu Giấy',
    city: 'Hà Nội',
    position: { lat: 21.0035153, lng: 105.6625269 },

    description:
      'Đại lộ Thăng Long là một tuyến đường chính của Hà Nội, nối liền từ ngoại thành Hà Nội vào trung tâm thành phố.',
    image: '/assets/images/covers/cover_6.jpg',
    postedAt: '2022-03-20',
    solution: 'Thường xuyên kiểm tra và bảo dưỡng đường bộ, tuyến đường để đảm bảo an toàn giao thông.',
    length: '30km',
    width: '6-12 làn đường',
    type: 'Đường cao tốc',
    material: 'Bê tông nhựa',
    start: '21.051165, 105.771274',
    end: '21.116925, 105.781581',
    speed: '80km/h',
    condition: 'Không',
    feature: 'Nối liền ngoại thành Hà Nội vào trung tâm thành phố',
    accident1: 1,
    accident2: 2,
    accident3: 3,
    accident4: 2,
  },
  {
    id: 7,
    road: 'Cầu Thanh Trì',
    district: 'Hoàng Mai',
    city: 'Hà Nội',
    description:
      'Cầu Thanh Trì là cây cầu bắc qua sông Hồng nối liền quận Hoàng Mai và Gia Lâm. Cầu có vị trí quan trọng trong việc kết nối các tuyến đường phía Nam của Hà Nội với các khu vực phía Bắc.',
    image: '/assets/images/covers/cover_8.jpg',
    postedAt: '2022-06-18',
    solution:
      'Nâng cấp cầu để tăng khả năng chịu tải, sửa chữa đường bộ, tăng cường kiểm soát tốc độ xe cộ và hạn chế các phương tiện vận tải quá tải trọng.',
    length: '2.8km',
    width: '6 làn đường',
    type: 'Cầu bắc qua sông',
    material: 'Bê tông cốt thép',
    start: '20.9749, 105.8683',
    position: { lat: 21.0277644, lng: 105.8341598 },
    end: '21.0043, 105.8887',
    speed: '60km/h',
    condition: 'Trong tình trạng tốt',
    feature:
      'Là cầu bắc qua sông Hồng có vai trò quan trọng trong việc kết nối các tuyến đường phía Nam của Hà Nội với các khu vực phía Bắc.',
    accident1: 1,
    accident2: 2,
    accident3: 0,
    accident4: 1,
  },
  {
    road: 'Hùng Vương',
    district: 'Phường 5',
    city: 'Cà Mau',
    description: 'Đông xe',
    solution: 'Đông xe',
    accident1: '0',
    accident2: '0',
    accident3: '0',
    accident4: '0',
    length: 'Đông xe',
    width: 'Đông xe',
    type: 'Đông xe',
    material: 'Đông xe',
    start: 'Đông xe',
    end: 'Đông xe',
    speed: 'Đông xe',
    condition: 'Đông xe',
    feature: 'Đông xe',
    postedAt: '2023-04-13T18:45:12.535Z',
    image: '/assets/images/covers/cover_15.jpg',
    position: { lat: 9.176736499999999, lng: 105.1512372 },
  },
  {
    road: 'Cộng hoà',
    district: 'Tân Bình',
    city: 'Hồ Chí Minh',
    description: 'Đoạn đường đông xe vào giờ cao điểm, có xe tải nhiều',
    solution: 'Giảm tốc độ, chú ý quan sát',
    accident1: '3',
    accident2: '0',
    accident3: '1',
    accident4: '0',
    length: '5000',
    width: '30',
    type: 'Đường bộ',
    material: 'Đường nhựa',
    start: '10.823, 106.629',
    end: '10.823, 106.629',
    speed: '60km/h',
    condition: 'Không ',
    feature: 'Không',
    postedAt: '2023-04-20T16:58:07.302Z',
    image: '/assets/images/covers/cover_12.jpg',
    position: {
      lat: 10.8019608,
      lng: 106.6477964,
    },
  },
];
